//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_Mongo_Bridge {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class MongoSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MongoSettings defaultInstance = ((MongoSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MongoSettings())));
        
        public static MongoSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://192.168.193.25:27017/productReport")]
        public string MongoConnectionString {
            get {
                return ((string)(this["MongoConnectionString"]));
            }
        }
    }
}
