USE [master]
GO

/****** Object:  Database [MusicDB]    Script Date: 9.8.2013 г. 20:06:41 ******/
CREATE DATABASE [MusicDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MusicDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\MusicDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MusicDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\MusicDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MusicDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MusicDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MusicDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MusicDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MusicDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MusicDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MusicDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MusicDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MusicDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MusicDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MusicDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MusicDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MusicDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MusicDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MusicDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MusicDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MusicDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MusicDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MusicDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MusicDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MusicDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MusicDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MusicDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MusicDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MusicDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MusicDB] SET RECOVERY FULL 
GO

ALTER DATABASE [MusicDB] SET  MULTI_USER 
GO

ALTER DATABASE [MusicDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MusicDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MusicDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MusicDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MusicDB] SET  READ_WRITE 
GO

