//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.EF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorExpens
    {
        public int VendorExpenseID { get; set; }
        public int VendorID { get; set; }
        public System.DateTime MonthDate { get; set; }
        public decimal Expnenses { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
